import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        sans: ["Hanken Grotesk", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["Georgia", "Times New Roman", "serif"],
        mono: ["ui-monospace", "JetBrains Mono", "SF Mono", "Menlo", "monospace"],
      },
      fontSize: {
        micro: ["11px", { lineHeight: "1", letterSpacing: "0.12em" }],
        caption: ["12px", { lineHeight: "16px" }],
        "body-sm": ["13px", { lineHeight: "18px" }],
        "body-md": ["14px", { lineHeight: "20px" }],
        "body-lg": ["16px", { lineHeight: "24px" }],
        "heading-sm": ["16px", { lineHeight: "22px", letterSpacing: "-0.005em" }],
        "heading-md": ["20px", { lineHeight: "26px", letterSpacing: "-0.01em" }],
        "heading-lg": ["24px", { lineHeight: "30px", letterSpacing: "-0.015em" }],
        "display-md": ["32px", { lineHeight: "38px", letterSpacing: "-0.015em" }],
        "display-lg": ["44px", { lineHeight: "50px", letterSpacing: "-0.02em" }],
        "display-xl": ["56px", { lineHeight: "60px", letterSpacing: "-0.025em" }],
      },
      colors: {
        border: "hsl(var(--border))",
        "border-subtle": "hsl(var(--border-subtle))",
        "border-default": "hsl(var(--border-default))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        raised: { DEFAULT: "hsl(var(--raised))", foreground: "hsl(var(--raised-foreground))" },
        sunken: { DEFAULT: "hsl(var(--sunken))", foreground: "hsl(var(--sunken-foreground))" },
        ink: { DEFAULT: "hsl(var(--ink))", foreground: "hsl(var(--ink-foreground))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        brand: {
          DEFAULT: "hsl(var(--brand))",
          foreground: "hsl(var(--brand-foreground))",
          soft: "hsl(var(--brand-soft))",
          deep: "hsl(var(--brand-deep))",
        },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        success: { DEFAULT: "hsl(var(--success))", foreground: "hsl(var(--success-foreground))", soft: "hsl(var(--success-soft))" },
        warning: { DEFAULT: "hsl(var(--warning))", foreground: "hsl(var(--warning-foreground))", soft: "hsl(var(--warning-soft))" },
        danger: { DEFAULT: "hsl(var(--danger))", foreground: "hsl(var(--danger-foreground))", soft: "hsl(var(--danger-soft))" },
        info: { DEFAULT: "hsl(var(--info))", foreground: "hsl(var(--info-foreground))", soft: "hsl(var(--info-soft))" },
        conf: {
          exact: "hsl(var(--conf-exact))",
          "exact-soft": "hsl(var(--conf-exact-soft))",
          high: "hsl(var(--conf-high))",
          "high-soft": "hsl(var(--conf-high-soft))",
          medium: "hsl(var(--conf-medium))",
          "medium-soft": "hsl(var(--conf-medium-soft))",
          low: "hsl(var(--conf-low))",
          "low-soft": "hsl(var(--conf-low-soft))",
          none: "hsl(var(--conf-none))",
          "none-soft": "hsl(var(--conf-none-soft))",
        },
        viz: {
          1: "hsl(var(--viz-1))",
          2: "hsl(var(--viz-2))",
          3: "hsl(var(--viz-3))",
          4: "hsl(var(--viz-4))",
          5: "hsl(var(--viz-5))",
          6: "hsl(var(--viz-6))",
          7: "hsl(var(--viz-7))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        focus: "var(--shadow-focus)",
      },
      transitionTimingFunction: {
        "out-quint": "cubic-bezier(0.16, 1, 0.3, 1)",
        "in-quint": "cubic-bezier(0.7, 0, 0.84, 0)",
        "in-out-quint": "cubic-bezier(0.65, 0, 0.35, 1)",
      },
      transitionDuration: {
        fast: "120ms",
        base: "180ms",
        slow: "240ms",
        slower: "320ms",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "slide-up": { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "slide-in-from-right": { from: { transform: "translateX(100%)" }, to: { transform: "translateX(0)" } },
        "slide-out-to-right": { from: { transform: "translateX(0)" }, to: { transform: "translateX(100%)" } },
        "bead-pulse": {
          "0%, 100%": { boxShadow: "0 0 0 0 hsl(var(--brand) / 0.35)" },
          "50%": { boxShadow: "0 0 0 6px hsl(var(--brand) / 0)" },
        },
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        "row-enter": {
          "0%": { opacity: "0", transform: "translateY(-2px)", boxShadow: "inset 2px 0 0 0 hsl(var(--brand))" },
          "60%": { opacity: "1", transform: "translateY(0)", boxShadow: "inset 2px 0 0 0 hsl(var(--brand))" },
          "100%": { opacity: "1", transform: "translateY(0)", boxShadow: "inset 0 0 0 0 transparent" },
        },
        "agent-shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "tenexity-mic-pulse": {
          "0%": { boxShadow: "0 0 0 0 hsl(var(--brand) / 0.45)" },
          "70%": { boxShadow: "0 0 0 6px hsl(var(--brand) / 0)" },
          "100%": { boxShadow: "0 0 0 0 hsl(var(--brand) / 0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 180ms cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-up": "slide-up 240ms cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-in-from-right": "slide-in-from-right 240ms cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-out-to-right": "slide-out-to-right 180ms cubic-bezier(0.7, 0, 0.84, 0)",
        "bead-pulse": "bead-pulse 2.4s cubic-bezier(0.16, 1, 0.3, 1) infinite",
        shimmer: "shimmer 1.6s ease-in-out infinite",
        "row-enter": "row-enter 480ms cubic-bezier(0.16, 1, 0.3, 1)",
        "agent-shimmer": "agent-shimmer 2s linear infinite",
        "tenexity-mic-pulse": "tenexity-mic-pulse 1.4s ease-out infinite",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
